#!/bin/bash

export ID=$(openssl rand -hex 16)
export WEIGHTS="./models/yolov8n.pt"
export DATA="./dataset/data.yaml"
export EPOCHS=5
export TIMEOUT=0 # if not 0, will override EPOCHS and train for number of hours.
export PATIENCE=5
export BATCH_SIZE=16
export IMG_SIZE=640
export SAVE_PERIOD=1
export CACHE=ram 
export DEVICE=cpu
export WORKERS=12
export PROJECT="runs/train/"
export NAME="exp" 
export EXIST_OK=0
export OPTIMIZER=auto 
export VERBOSE=True
export SEED=0
export DETERMINISTIC=True
export COSINE_LEARNING_RATE=False
export CLOSE_MOSAIC=10 
export RESUME=False # true if you want to resume training
export AUTOMATIC_MIXED_PRECISION=True
export FRACTION=1.0
export PROFILE=False # Enables profiling of ONNX and TensorRT speeds during training, useful for optimizing model deployment.
export FREEZE=0
export FREEZE_ON=False
export INITIAL_LEARNING_RATE=0.01
export FINAL_LEARNING_RATE=0.01 # Final learning rate as a fraction of the initial rate = (`INITIAL_LEARNING_RATE` * `FINAL_LEARNING_RATE`), used in conjunction with schedulers to adjust the learning rate over time.
export MOMENTUM=0.937
export WEIGHT_DECAY=0.0005
export WARMUP_EPOCHS=1
export WARMUP_MOMENTUM=0.8
export WARMUP_BIAS_LEARNING_RATE=0.1
export BOX_LOSS_WEIGHT=7.5
export CLASSIFICATION_LOSS_WEIGHT=0.5
export DISTRIBUTED_FOCAL_LOSS_WEIGHT=1.5
export POSE_LOSS_WEIGHT=12.0
export KEYPOINT_OBJECTNESS_LOSS_WEIGHT=2.0 
export LABEL_SMOOTHING=0.0 
export NOMINAL_BATCH_SIZE=64 
export OVERLAP_MASK=1
export MASK_RATIO=4
export DROPOUT=0.0
export VALIDATE=True
export PLOTS=True
export LOGGER=CLEAR_ML # 0, COMET_ML or CLEAR_ML

