#!/bin/bash
export PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

echo $#
source "${PROJECT_DIR}/src/func.sh"

# Call get_ddp_options with the remaining arguments
get_ddp_options "$@"

echo "Create venv:" $CREATE_VENV
echo "Task:" $TASK
echo "NPROC_PER_NODE: $NPROC_PER_NODE"
echo "NNODES: $NNODES"
echo "NODE_RANK: $NODE_RANK"
echo "MASTER_ADDR: $MASTER_ADDR"
echo "MASTER_PORT: $MASTER_PORT"

trap cleanup_env EXIT

source "${PROJECT_DIR}/src/setup_env.sh"

torchrun \
    --nproc_per_node="$NPROC_PER_NODE"\
    --nnodes="$NNODES" \
    --node_rank="$NODE_RANK" \
    --master_addr="$MASTER_ADDR" \
    --master_port="$MASTER_PORT" \
    "${PROJECT_DIR}/src/train-ddp.py" 

cleanup_env