#!/bin/bash
export PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

source "${PROJECT_DIR}/src/func.sh"

get_options "$@"

echo "Create venv:" $CREATE_VENV
echo "Task:" $TASK

trap cleanup_env EXIT

source "${PROJECT_DIR}/src/setup_env.sh"
python3 "${PROJECT_DIR}/src/train.py"
cleanup_env