logger: 0
params:
  amp: true
  auto_augment: randaugment
  batch: 16
  box: 7.5
  cache: false
  close_mosaic: 10
  cls: 0.5
  conf: null
  copy_paste: 0.0
  cos_lr: false
  crop_fraction: 1.0
  data: datasets/data.yaml
  degrees: 0.0
  deterministic: true
  device: auto
  dfl: 1.5
  dnn: false
  dropout: 0.0
  epochs: 100
  erasing: 0.4
  exist_ok: false
  fliplr: 0.5
  flipud: 0.0
  fraction: 1.0
  freeze: None
  half: false
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  imgsz: 640
  iou: 0.7
  kobj: 1.0
  label_smoothing: 0.0
  lr0: 0.01
  lrf: 0.01
  mask_ratio: 4
  max_det: 300
  mixup: 0.0
  momentum: 0.937
  mosaic: 1.0
  multi_scale: false
  name: exp1
  nbs: 64
  optimizer: auto
  overlap_mask: true
  patience: 100
  perspective: 0.0
  plots: true
  pose: 12.0
  pretrained: true
  profile: false
  project: runs
  rect: false
  resume: false
  save: true
  save_hybrid: false
  save_json: false
  save_period: -1
  scale: 0.5
  seed: 0
  shear: 0.0
  single_cls: false
  split: val
  time: null
  translate: 0.1
  val: true
  verbose: true
  warmup_bias_lr: 0.1
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  weight_decay: 0.0005
  workers: 8
weights: yolov8n.pt
